sudo: required
services:
  - docker

before_install:
  - docker build -t weemanjz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run weemanjz/react-test npm test -- --coverage

after_success:
  - docker build -t weemanjz/multi-client ./client
  - docker build -t weemanjz/multi-nginx ./nginx
  - docker build -t weemanjz/multi-server ./server
  - docker build -t weemanjz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push weemanjz/multi-client
  - docker push weemanjz/multi-nginx
  - docker push weemanjz/multi-server
  - docker push weemanjz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-274930267490
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
